env_type: 'CartPole-v1'
# env_type : MountainCar-v0
budget: 100
max_depths: [2, 4, 8, 10]
selection_strategy : UCT
# selection_strategy : eps-Greedy
discount: 1.0
ucb_c: 100.0
eps: 0.1
debug : False
num_seeds: 5
max_depth: 50