env_type: 'gridworld'
budget: 1000
max_depths: [5, 10, 20, 40, 100]
selection_strategy : UCT
# selection_strategy : eps-Greedy
discount: 0.9
ucb_c: 50.0
eps: 0.1
debug : False
num_seeds: 10
max_depth: 200